export const ListTypes = {
    ADD_MOVIE_TO_WATCHLIST:"ADD_MOVIE_TO_WATCHLIST",
    REMOVE_MOVIE_FROM_WATCHLIST:"REMOVE_MOVIE_FROM_WATCHLIST",
    ADD_MOVIE_TO_WATCHED:"ADD_MOVIE_TO_WATCHED",
    REMOVE_MOVIE_FROM_WATCHED:"REMOVE_MOVIE_FROM_WATCHED",
    ADD_MOVIE_BACKTO_WATCHLIST:"ADD_MOVIE_BACKTO_WATCHLIST"

}